version: '3.9'
services:

  api:
    image: apod-img-store
    container_name: apod-img-store-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=host=postgresDB user=apoduser password=apoduserpassword dbname=apod sslmode=disable
      - SERVER_PORT=8080
    depends_on:
      postgresDB:
        condition: service_healthy

  postgresDB:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      APP_DB_NAME: "apod"
      APP_DB_USER: "apoduser"
      APP_DB_PASS: "apoduserpassword"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./db_scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: {}